### ISSUE TITLE
Spotify wont run

### ISSUE THREAD

**Issue by scorthyn** [master131/BlockTheSpot#1]
After installing this the spotify client doesnt run, If i delete the dll it runs fine.

**Comment by master131** [comment]
What version of Spotify do you have installed and what OS are you running? You can check by clicking the three dots in the corner of the program and clicking Help then About Spotify.

**Comment by scorthyn** [comment]
sorry my bad, i had ezblock in conflit, installed latest version on windows 10 and now it runs fine. thanks so much

**Comment by master131** [comment]
No problem.
