### ISSUE TITLE
Crashing every 10-15 minutes with new Spotify update

### ISSUE THREAD

**Issue by HalfOfAKebab** [master131/BlockTheSpot#11]
Since updating to 1.1.1.346.gaebf3c8d, Spotify crashes with the DLL installed every ten minutes or so

**Comment by master131** [comment]
I have yet to receive the latest update so I can't look into it until I do.

**Comment by KaleidonKep99** [comment]
1.1.1 seems to be an UWP-exclusive release (for now).
I tried downloading it in a Windows 10 VM, and the Win32 setup from the official website still downloads 1.1.0.237.g378f6f25, while the Microsoft Store downloads yours.

**Comment by HalfOfAKebab** [comment]
I've found a workaround. Deny write access to the folder Spotify downloads updates to, and download an older version of Spotify.

https://www.reddit.com/r/spotify/comments/alw999/new_spotify_update_blocking_method/

https://www.filehorse.com/download-spotify/old-versions/

I'm using 1.0.98.78.gb45d2a6b (available from FileHorse) with the update folder blocked, and it's working perfectly again

**Comment by HalfOfAKebab** [comment]
> 1.1.1 seems to be an UWP-exclusive release (for now).
> I tried downloading it in a Windows 10 VM, and the Win32 setup from the official website still downloads 1.1.0.237.g378f6f25, while the Microsoft Store downloads yours.

Weird, I'm definitely not using the UWP version

**Comment by rpodric** [comment]
Win32 apps are also delivered via the Store, not just UWP.

**Comment by CHEF-KOCH** [comment]
UWP apps are ALWAYS delivered first before Win32 (this usually takes 4-7 days). 

The new update Spotify 1.1.1.348.g9064793a still works with BlockTheSpot.

**Comment by Bec-de-Xorbin** [comment]
I still don't get the update through "normal" channels and if there's some others too and want to update, here's the link to installer:
http://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.1.348.g9064793a-14.exe

EDIT: I can also confirm that BlockTheSpot still works without crashing. EDIT3: After several hours of listening, Spotify crashed. Could be something else than BlockTheSpot too, of course....

EDIT2: @HalfOfAKebab's older version is available here if someone wants to try it (why though):
http://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.1.346.gaebf3c8d-11.exe

**Comment by master131** [comment]
Thanks for those links @Bec-de-Xorbin.

BlockTheSpot has been updated; I disabled all the fallback patches for 1.1.1.xxx and above. See if that stops the crashing.

**Comment by Bec-de-Xorbin** [comment]
No crashes anymore. You can close this issue as solved.
