### ISSUE TITLE
Compatability with Microsoft Store app

### ISSUE THREAD

**Issue by LawnSounds** [master131/BlockTheSpot#15]
Would it be possible to make this compatible with the Microsoft Store version?

**Comment by MasicoreLord** [comment]
Doubt it.

**Comment by LawnSounds** [comment]
Why? Isn’t it fundamentally the same program? 
No, it isn’t encrypted just because it’s a UWP app, but yea the folders are write protected - it would require some permission changing code added in that regard...

**Comment by master131** [comment]
I don't plan to support it due to needing to mess around with ACLs and potentially breaking Store apps. You're free to manually drop the DLL in the corresponding folder but it's not something I'm willing to officially support.
