### ISSUE TITLE
Installation/updates force microsoft store version

### ISSUE THREAD

**Issue by Cybercorvid** [master131/BlockTheSpot#18]
Unless doing something completely wrong, even when downloading the offline method for spotify, the user gets the microsoft store version.  It being placed within WindowsApps does not allow anything to view or edit files within the folder.  Allowing it to run untouched.

**Comment by raven0034** [comment]
I can't say I ever seen this issue. I'm using Windows 10 and when using the normal desktop version (ie exe version not appx), any auto-updates come in .exe form, and Microsoft Store does not even recognise the exe version even being present, so I'm not entirely sure how you've come across this issue.

**Comment by Cybercorvid** [comment]
I'm not sure it's necessarily the microsoft version, but the installer believes it is because the spotify program is only downloaded in the windowsApps folder. If you have any ideas I am open to hearing.

**Comment by master131** [comment]
Have you read through issue #6? Specifically the last 3 comments.

**Comment by jakey1995abc** [comment]
I have a feeling Microsoft sometimes installs Spotify (app store version) automatically when you fresh install Windows. And until you manually uninstall the app store version, the .exe version will not install correctly. This was the case for me a few days ago when I reinstalled Windows 10.

**Comment by Cybercorvid** [comment]
This seemed to solve the problem.  
The download was always being placed into the WindowsApps folder not allowing the administrator to view or edit anything.  Uninstalling spotify and trying to re-download the program never seemed to help, even when troubleshooting the program and then choosing the "Windows 7 version".  

Previously I had uninstalled the microsoft store using powershell, although I do not know whether or not this actually helps.

If you do what is explained [here](https://winaero.com/blog/how-to-take-ownership-and-get-full-access-to-files-and-folders-in-windows-10/) for the folder named WindowsApps in the Program Files folder to give yourself access to everything inside, you will then be able to edit the files containing spotify.  

After doing that (keeping spotify closed the entire time) I moved everything in there into a new folder that I named "spotify" in the Program Files folder, and deleted the entire folder within WindowsApps. Then manually adding the netutils.dll file into the spotify folder I created, and running spotify. This solved the problem and now master131's program now works.

Edit: I forgot to mention that I did delete the "migrator" file (I believe that is what it was called) before moving all the files over to the new folder.

**Comment by Cybercorvid** [comment]
Also, @master131, I did read through issue #6 but had a problem while booting in safe mode. My system is still on wifi, and safe mode only allowed Ethernet, so I was unable to re-download spotify.

**Comment by master131** [comment]
@Cybercorvid I'm glad you managed to get it to work eventually. I created a downgrade script (on the main page) which may help out users facing the migration scenario from Spotify. If you could try it out and see if it works for you as well that would be great as I can't reproduce the issue on my end.

**Comment by 7evenlxrd** [comment]
BlockTheSpot by master131 on Microsoft Store Edition? YES!
I found this way alone. By 7evenlxrd ;)

Requiments:

netutils.dll (this is BlockTheSpot)
You need Ubuntu (installed on disk or live cd/usb doesn't matters).
Steps:
Run Ubuntu
Run File Explorer (in ubuntu), click on Other Locations then click on your disk with Windows 10.
Go to where is a BlockTheSpot (netutils.dll) and copy this
Go to Program Files, double click WindowsApps.
Find a Spotify folder (SpotifyAB.SpotifyMusic_ and something)
Go to Properties, Permissons and give all permissions (create and delete files)
Paste BlockTheSpot (netutils.dll) to Spotify folder.
Restart to Windows 10.
Enjoy ;)

Links:
Ubuntu: https://www.ubuntu.com/download/desktop
UUI (to make live usb): https://www.pendrivelinux.com/universal-usb-installer-easy-as-1-2-3/
BlockTheSpot: https://github.com/master131/BlockTheSpot

**Comment by 7evenlxrd** [comment]
BlockTheSpot by master131 on Microsoft Store Edition? YES!
I found this way alone. By 7evenlxrd ;)

Requiments:

1. netutils.dll (this is BlockTheSpot)
2. You need Ubuntu (installed on disk or live cd/usb doesn't matters).
Steps:
1. Run Ubuntu
2. Run File Explorer (in ubuntu), click on Other Locations then click on your disk with Windows 10.
3. Go to where is a BlockTheSpot (netutils.dll) and copy this
4. Go to Program Files, double click WindowsApps.
5. Find a Spotify folder (SpotifyAB.SpotifyMusic_ and something)
6. Go to Properties, Permissons and give all permissions (create and delete files)
7. Paste BlockTheSpot (netutils.dll) to Spotify folder.
8. Restart to Windows 10.
Enjoy ;)

Links:
Ubuntu: https://www.ubuntu.com/download/desktop
UUI (to make live usb): https://www.pendrivelinux.com/universal-usb-installer-easy-as-1-2-3/
BlockTheSpot: https://github.com/master131/BlockTheSpot
