### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by scorthyn** [master131/BlockTheSpot#2]
Sorry to bother again but its actually not working on my desktop. Clean install and blockthespot actually doesnt run spotify. Is there any dependencies or services that might be active on windows?

Using windows 10 Insider build 18262
Spotify desktop latest version

**Comment by master131** [comment]
There could be a difference in the memory layout which is causing a crash. I'll have to look into this further.

**Comment by master131** [comment]
[netutils.zip](https://github.com/master131/BlockTheSpot/files/2536620/netutils.zip)

Can you try this copy of netutils.dll (place next to Spotify.exe) and see if there's any improvement?

**Comment by master131** [comment]
Please try the latest version and see if there is any improvement.

**Comment by scorthyn** [comment]
Still the same unfortunately , using the same build on my laptop and it works fine. Genuinely dot know whats wrong. Thanks anyway, its amazing overall

**Comment by scorthyn** [comment]
Its working correctly, the problem was on my end, fucked up windows overall. Thanks a lot for this
