### ISSUE TITLE
Would it be possible for you to put the source code so we can compile this dll ourselves?

### ISSUE THREAD

**Issue by GroxicTinch** [master131/BlockTheSpot#3]
I'm a bit iffy about dropping a dll file in with a program that requires a log in, and I am sure I wont be the only person, as much as I want to use this and believe you to just be some helpful person out there, there is always the chance for something malicious and having the source code available for people to see that it is safe

**Comment by master131** [comment]
I'm afraid doing so would make it subject to takedown from Spotify and make it easier for them to patch it. You are free to reverse engineer it (ie. using IDA, OllyDbg, etc) or use the DLL in an isolated environment (ie. virtual machine, dummy account) to determine its safety. This mod only benefits those with free Spotify accounts anyway. If you have concerns or qualms, then you are free to not use it - it's your choice.

**Comment by master131** [comment]
After some deliberation I've decided to add the source as many people have requested it from me. I just had to clean it up (removing unused code and adding some comments) and add the proper license before adding it.
